// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caycorcsoukuqjlooekc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNheWNvcmNzb3VrdXFqbG9vZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgzMzA5MzYsImV4cCI6MjA0MzkwNjkzNn0.r_tojTZCmdCiQuRjpP9Gpaf_oYkiZB0gVCSQFyXbr44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);